#!/usr/bin/env python3
"""Keeps the SYSKit API reference true to the code.

    python3 scripts/api-docs.py            # check: fail if the reference is stale or the docs name something gone
    python3 scripts/api-docs.py generate   # rewrite SYSKIT-API.md from the source

SYSKIT-API.md lists every public top-level type, and every public `sys…` modifier or value on a system type, with
the first sentence of its doc comment. It is generated, so it cannot be forgotten: a new public type changes the
file, and `validate.sh` fails until the change is committed.

The check also reads the handwritten docs and fails on any `SYS…` or `sys…` name that no longer appears anywhere in
the SYSKit source: a renamed or deleted type that the PLAYBOOK still teaches.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "SYSKIT-API.md"
DEBT = ROOT / "scripts" / "api-docs.debt"
SOURCES = sorted((ROOT / "SPM").glob("*/Sources"))

DOCS = ["PLAYBOOK.md", "README.md", "tools/PES/shared/README.md"]
DOC_FOLDERS = ["templates/docs", "decisions", "skills"]

NOT_CODE = {
    "SYSKit", "SYSKIT", "SYSFirebase", "SYSFirebaseCrashlytics", "SYSContentID", "SYSAppStoreID", "SYSStored",
}

TYPE = re.compile(
    r"^(?:@\w+(?:\([^)]*\))?\s+)*public\s+(?:final\s+)?(?:indirect\s+)?(class|struct|enum|protocol|actor|typealias)\s+(\w+)"
)
EXTENSION = re.compile(r"^(?:@\w+(?:\([^)]*\))?\s+)*public\s+extension\s+(\w+)")
MEMBER = re.compile(
    r"^\s+(?:@\w+(?:\([^)]*\))?\s+)*(?:public\s+)?(?:static\s+)?(?:func|var|let)\s+((?:sys|SYS)[A-Za-z0-9]*)"
)
HIDDEN = re.compile(r"\b(private|fileprivate|internal)\b")
IDENTIFIER = re.compile(r"\b(?:SYS|sys)[A-Z][A-Za-z0-9]*")


def summary(doc: list[str]) -> str:
    text = " ".join(line.strip() for line in doc if line.strip())
    text = re.sub(r"`", "", text)
    text = re.sub(r"\s+", " ", text)
    first = re.split(r"(?<=[.!?])\s", text, maxsplit=1)[0].strip()
    first = first.replace("|", "\\|")
    return (first[:157] + "...") if len(first) > 160 else first


def scan(path: Path) -> list[tuple[str, str, str, str]]:
    """(kind, name, owner, summary) for each public thing in one file."""
    found, doc, owner = [], [], None
    for line in path.read_text(errors="replace").split("\n"):
        stripped = line.strip()
        if stripped.startswith("///"):
            doc.append(stripped[3:])
            continue
        if stripped.startswith("@") and not stripped.startswith("@MainActor public") and "public" not in stripped:
            continue
        match = TYPE.match(line)
        if match:
            found.append((match.group(1), match.group(2), "", summary(doc)))
            owner = None
        else:
            extension = EXTENSION.match(line)
            if extension:
                owner = extension.group(1)
            elif line and not line[0].isspace() and not stripped.startswith(("}", "#", "//")):
                owner = None
            member = MEMBER.match(line)
            if member and owner and not HIDDEN.search(line):
                found.append(("member", member.group(1), owner, summary(doc)))
        doc = []
    return found


def playbook_descriptions() -> dict[str, str]:
    """First sentence of the PLAYBOOK table row that names a symbol first: the curated description."""
    found = {}
    for line in (ROOT / "PLAYBOOK.md").read_text().split("\n"):
        cells = [cell.strip() for cell in line.strip().strip("|").split("|")]
        if not line.startswith("|") or len(cells) < 2 or len(cells[1]) < 40:
            continue
        description = summary([cells[1]])
        for name in IDENTIFIER.findall(cells[0]):
            found.setdefault(name, description)
    return found


def collect() -> list[tuple[str, str, str, str, str, str]]:
    """(package, domain, kind, name, owner, description) for everything public."""
    described = playbook_descriptions()
    rows = []
    for source in SOURCES:
        package = source.parent.name
        base = source / package
        for path in sorted(base.rglob("*.swift")):
            relative = path.relative_to(base)
            domain = relative.parts[0] if len(relative.parts) > 1 else ""
            for kind, name, owner, text in scan(path):
                rows.append((package, domain, kind, name, owner, text or described.get(name, "")))
    return rows


def render() -> str:
    lines = [
        "# SYSKit API",
        "",
        "Generated by `scripts/api-docs.py` from the source. Do not edit. Every public type, and every public `sys…`",
        "modifier or value on a system type, with the first sentence of its doc comment. The PLAYBOOK says when to use",
        "what; this says what exists.",
        "",
    ]
    rows = collect()
    for package, domain in sorted({(r[0], r[1]) for r in rows}):
        section = [r for r in rows if (r[0], r[1]) == (package, domain)]
        lines += [f"## {package}" + (f" / {domain}" if domain else ""), "", "| Name | Kind | Summary |", "|---|---|---|"]
        unique = {(r[2], r[3], r[4]): r for r in section}.values()
        for _, _, kind, name, owner, text in sorted(unique, key=lambda r: (r[2] == "member", r[3], r[4])):
            label = f"`{owner}.{name}`" if owner else f"`{name}`"
            lines.append(f"| {label} | {'on ' + owner if kind == 'member' else kind} | {text or '—'} |")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def known_names() -> set[str]:
    names = set()
    for source in SOURCES:
        for path in source.rglob("*.swift"):
            names.update(IDENTIFIER.findall(path.read_text(errors="replace")))
    return names


def doc_files() -> list[Path]:
    files = [ROOT / name for name in DOCS if (ROOT / name).is_file()]
    for folder in DOC_FOLDERS:
        files += sorted((ROOT / folder).rglob("*.md"))
    return files


def stale_references() -> list[str]:
    known = known_names() | NOT_CODE
    problems = []
    for path in doc_files():
        for number, line in enumerate(path.read_text(errors="replace").split("\n"), 1):
            for name in sorted(set(IDENTIFIER.findall(line))):
                if name not in known:
                    problems.append(f"{path.relative_to(ROOT)}:{number}: `{name}` is not in the SYSKit source")
    return problems


def undescribed() -> list[str]:
    return sorted({name for _, _, _, name, _, text in collect() if not text})


def debt_problems() -> list[str]:
    debt = {line.split("#")[0].strip() for line in DEBT.read_text().split("\n")} - {""} if DEBT.is_file() else set()
    current = set(undescribed())
    problems = [
        f"`{name}` is public and has no description — add a doc comment or a PLAYBOOK row, "
        f"or (debt) add it to scripts/api-docs.debt"
        for name in sorted(current - debt)
    ]
    problems += [
        f"`{name}` is described now — remove it from scripts/api-docs.debt"
        for name in sorted(debt - current)
    ]
    return problems


def main() -> int:
    if len(sys.argv) > 1 and sys.argv[1] == "generate":
        OUTPUT.write_text(render())
        print(f"wrote {OUTPUT.relative_to(ROOT)}")
        return 0
    if len(sys.argv) > 1 and sys.argv[1] == "debt":
        DEBT.write_text("# Public SYSKit names with no description yet. Shrink this list; do not grow it.\n"
                        + "\n".join(undescribed()) + "\n")
        print(f"wrote {DEBT.relative_to(ROOT)} ({len(undescribed())} names)")
        return 0

    problems = stale_references() + debt_problems()
    current = OUTPUT.read_text() if OUTPUT.is_file() else ""
    if current != render():
        problems.append("SYSKIT-API.md is out of date — run: python3 scripts/api-docs.py generate")
    for problem in problems:
        print(f"  {problem}")
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
